### ISSUE TITLE
A-star with admissible heuristics is not always returning optimal solutions.

### ISSUE THREAD

**Issue by Tobias-Opsahl** [RobertSasak/Prolog-Planning-Library#7]
A-star should always return optimal solutions with admissible (non-overestimating) heuristics, but it does not. h_max is admissible, _h_diff_ is it in all the problems implemented. _h_0_ is no heuristic, so it is equivalent to dijsktra. However, even dijkstra is not always returning optimal solutions, which it should. This code demonstrates the problem: 
```
:-[readFile, parseProblem, parseDomain, common].
:- ['a-star', forward, h_0].
:- solve_files('test/hanoi/domain-hanoi.pddl', 'test/hanoi/hanoi3.pddl').
```
The path has length 9, but the best way to solve hanoi3 is with only 7 moves. If you look at the first 2 actions, disc1 is put from peg1 to peg2, then put from peg2 to peg3. This is obviously non-optimal since it could have just been put directly onto peg 3.

The reason the bug is present is that nodes are not being checked if they are visited in a proper way. Every time a new node is explored, it is added to the queue. The next step of a-star simply pops of the heap (_get_from_heap_) and does not check if the node is already visited. This means that the algorithms re-explore even when the path has just gone in circles, which is very wasteful. Finally, when the solution backtracks, there might be multiple paths. The predicate "solution" in common.pl choses a the path arbitrarily, instead of finding the path that corresponds to the optimal solution.

**Comment by RobertSasak** [comment]
Well spotted. I merged your https://github.com/RobertSasak/Prolog-Planning-Library/pull/6 that add corresponding tests. Feel free to create another PR that address this issue.

**Comment by Tobias-Opsahl** [comment]
With the new merge, the bug can easier be demonstrated with the file ```testing.pl```. Simply comment in a heuristic (there are examples in the code), and compile the code. The heuristics h_0, h_max and h_diff are admissible and should pass all the tests, but they do not (h_diff is admissible under the assumption for the problems we work with, in some strange scenarios it might not be). Note that h_add should not necessary pass all the tests, since it can overestimate and is not admissible.
